
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action InfoAction;
	
	private global::Gtk.Action dialogInfoAction;
	
	private global::Gtk.Action AboutMenuItem;
	
	private global::Gtk.Action dfgAction;
	
	private global::Gtk.Action dialogQuestionAction;
	
	private global::Gtk.Action EditAction;
	
	private global::Gtk.Action ParametersAction;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action ExitMenuItem;
	
	private global::Gtk.Action CacheParametersAction;
	
	private global::Gtk.Action BpredParametersAction;
	
	private global::Gtk.Action OutorderParametersAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar1;
	
	private global::Gtk.Fixed fixed2;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TextView resultsText;
	
	private global::Gtk.Button button1;
	
	private global::Gtk.Label label3;
	
	private global::Gtk.CheckButton susanCheckBox;
	
	private global::Gtk.CheckButton basicmathSmallCheckBox;
	
	private global::Gtk.CheckButton basicmathLargeCheckBox;
	
	private global::Gtk.Label label8;
	
	private global::Gtk.Entry numberOfGenerations;
	
	private global::Gtk.Label label2;
	
	private global::Gtk.Entry numberOfCromozoms;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.Label label4;
	
	private global::Gtk.Label label6;
	
	private global::Gtk.Entry crossoverPercentageTextBox;
	
	private global::Gtk.RadioButton rouletteRadioButton;
	
	private global::Gtk.RadioButton tournamentRadioButton;
	
	private global::Gtk.RadioButton elitistRadioButton;
	
	private global::Gtk.Image image6;
	
	private global::Gtk.Label label9;
	
	private global::Gtk.Label label5;
	
	private global::Gtk.Label label7;
	
	private global::Gtk.Entry elitesPercentageTextBox;
	
	private global::Gtk.Entry mutationOccuranceTextBox;
	
	private global::Gtk.Entry mutationPercentageTextBox;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.InfoAction = new global::Gtk.Action ("InfoAction", global::Mono.Unix.Catalog.GetString ("Info"), null, null);
		this.InfoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.InfoAction, null);
		this.dialogInfoAction = new global::Gtk.Action ("dialogInfoAction", global::Mono.Unix.Catalog.GetString ("Help"), null, "gtk-dialog-info");
		this.dialogInfoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.dialogInfoAction, null);
		this.AboutMenuItem = new global::Gtk.Action ("AboutMenuItem", global::Mono.Unix.Catalog.GetString ("About"), null, "gtk-dialog-info");
		this.AboutMenuItem.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutMenuItem, null);
		this.dfgAction = new global::Gtk.Action ("dfgAction", global::Mono.Unix.Catalog.GetString ("dfg"), null, null);
		this.dfgAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("dfg");
		w1.Add (this.dfgAction, null);
		this.dialogQuestionAction = new global::Gtk.Action ("dialogQuestionAction", global::Mono.Unix.Catalog.GetString ("Help"), null, "gtk-dialog-question");
		this.dialogQuestionAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.dialogQuestionAction, null);
		this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
		w1.Add (this.EditAction, null);
		this.ParametersAction = new global::Gtk.Action ("ParametersAction", global::Mono.Unix.Catalog.GetString ("Parameters"), null, null);
		this.ParametersAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Parameters");
		w1.Add (this.ParametersAction, null);
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.ExitMenuItem = new global::Gtk.Action ("ExitMenuItem", global::Mono.Unix.Catalog.GetString ("Exit"), null, null);
		this.ExitMenuItem.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exit");
		w1.Add (this.ExitMenuItem, null);
		this.CacheParametersAction = new global::Gtk.Action ("CacheParametersAction", global::Mono.Unix.Catalog.GetString ("Cache Parameters"), null, null);
		this.CacheParametersAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cache Parameters");
		w1.Add (this.CacheParametersAction, null);
		this.BpredParametersAction = new global::Gtk.Action ("BpredParametersAction", global::Mono.Unix.Catalog.GetString ("Bpred Parameters"), null, null);
		this.BpredParametersAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Bpred Parameters");
		w1.Add (this.BpredParametersAction, null);
		this.OutorderParametersAction = new global::Gtk.Action ("OutorderParametersAction", global::Mono.Unix.Catalog.GetString ("Outorder Parameters"), null, null);
		this.OutorderParametersAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Outorder Parameters");
		w1.Add (this.OutorderParametersAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("VEX Simulation | Genetic Algorithm");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='ExitMenuItem' action='ExitMenuItem'/></menu><menu name='EditAction' action='EditAction'><menu name='ParametersAction' action='ParametersAction'><menuitem name='CacheParametersAction' action='CacheParametersAction'/><menuitem name='BpredParametersAction' action='BpredParametersAction'/><menuitem name='OutorderParametersAction' action='OutorderParametersAction'/></menu></menu><menu name='InfoAction' action='InfoAction'><menuitem name='dialogQuestionAction' action='dialogQuestionAction'/><menuitem name='AboutMenuItem' action='AboutMenuItem'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.HeightRequest = 100;
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.resultsText = new global::Gtk.TextView ();
		this.resultsText.WidthRequest = 300;
		this.resultsText.HeightRequest = 200;
		this.resultsText.CanFocus = true;
		this.resultsText.Name = "resultsText";
		this.resultsText.Editable = false;
		this.GtkScrolledWindow.Add (this.resultsText);
		this.fixed2.Add (this.GtkScrolledWindow);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.GtkScrolledWindow]));
		w4.X = 14;
		w4.Y = 94;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.button1 = new global::Gtk.Button ();
		this.button1.CanFocus = true;
		this.button1.Name = "button1";
		this.button1.UseUnderline = true;
		this.button1.Label = global::Mono.Unix.Catalog.GetString ("Start Simulation");
		this.fixed2.Add (this.button1);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.button1]));
		w5.X = 12;
		w5.Y = 322;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Benchmarks");
		this.fixed2.Add (this.label3);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label3]));
		w6.X = 348;
		w6.Y = 87;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.susanCheckBox = new global::Gtk.CheckButton ();
		this.susanCheckBox.CanFocus = true;
		this.susanCheckBox.Name = "susanCheckBox";
		this.susanCheckBox.Label = global::Mono.Unix.Catalog.GetString ("Susan");
		this.susanCheckBox.Active = true;
		this.susanCheckBox.DrawIndicator = true;
		this.susanCheckBox.UseUnderline = true;
		this.fixed2.Add (this.susanCheckBox);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.susanCheckBox]));
		w7.X = 346;
		w7.Y = 109;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.basicmathSmallCheckBox = new global::Gtk.CheckButton ();
		this.basicmathSmallCheckBox.CanFocus = true;
		this.basicmathSmallCheckBox.Name = "basicmathSmallCheckBox";
		this.basicmathSmallCheckBox.Label = global::Mono.Unix.Catalog.GetString ("BasicMath Small");
		this.basicmathSmallCheckBox.DrawIndicator = true;
		this.basicmathSmallCheckBox.UseUnderline = true;
		this.fixed2.Add (this.basicmathSmallCheckBox);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.basicmathSmallCheckBox]));
		w8.X = 346;
		w8.Y = 134;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.basicmathLargeCheckBox = new global::Gtk.CheckButton ();
		this.basicmathLargeCheckBox.CanFocus = true;
		this.basicmathLargeCheckBox.Name = "basicmathLargeCheckBox";
		this.basicmathLargeCheckBox.Label = global::Mono.Unix.Catalog.GetString ("BasicMath Large");
		this.basicmathLargeCheckBox.DrawIndicator = true;
		this.basicmathLargeCheckBox.UseUnderline = true;
		this.fixed2.Add (this.basicmathLargeCheckBox);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.basicmathLargeCheckBox]));
		w9.X = 346;
		w9.Y = 159;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Selection Mode");
		this.fixed2.Add (this.label8);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label8]));
		w10.X = 530;
		w10.Y = 88;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.numberOfGenerations = new global::Gtk.Entry ();
		this.numberOfGenerations.WidthRequest = 60;
		this.numberOfGenerations.CanFocus = true;
		this.numberOfGenerations.Name = "numberOfGenerations";
		this.numberOfGenerations.Text = global::Mono.Unix.Catalog.GetString ("5");
		this.numberOfGenerations.IsEditable = true;
		this.numberOfGenerations.InvisibleChar = '●';
		this.fixed2.Add (this.numberOfGenerations);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.numberOfGenerations]));
		w11.X = 510;
		w11.Y = 268;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Number of Generations: ");
		this.fixed2.Add (this.label2);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label2]));
		w12.X = 348;
		w12.Y = 272;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.numberOfCromozoms = new global::Gtk.Entry ();
		this.numberOfCromozoms.WidthRequest = 60;
		this.numberOfCromozoms.CanFocus = true;
		this.numberOfCromozoms.Name = "numberOfCromozoms";
		this.numberOfCromozoms.Text = global::Mono.Unix.Catalog.GetString ("10");
		this.numberOfCromozoms.IsEditable = true;
		this.numberOfCromozoms.InvisibleChar = '●';
		this.fixed2.Add (this.numberOfCromozoms);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.numberOfCromozoms]));
		w13.X = 510;
		w13.Y = 232;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Number of Cromozoms: ");
		this.fixed2.Add (this.label1);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label1]));
		w14.X = 348;
		w14.Y = 237;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Choose a parameter");
		this.fixed2.Add (this.label4);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label4]));
		w15.X = 348;
		w15.Y = 204;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("CrossOver Chance: ");
		this.fixed2.Add (this.label6);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label6]));
		w16.X = 348;
		w16.Y = 308;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.crossoverPercentageTextBox = new global::Gtk.Entry ();
		this.crossoverPercentageTextBox.WidthRequest = 60;
		this.crossoverPercentageTextBox.CanFocus = true;
		this.crossoverPercentageTextBox.Name = "crossoverPercentageTextBox";
		this.crossoverPercentageTextBox.Text = global::Mono.Unix.Catalog.GetString ("50");
		this.crossoverPercentageTextBox.IsEditable = true;
		this.crossoverPercentageTextBox.InvisibleChar = '●';
		this.fixed2.Add (this.crossoverPercentageTextBox);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.crossoverPercentageTextBox]));
		w17.X = 510;
		w17.Y = 303;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.rouletteRadioButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Roulette Wheel"));
		this.rouletteRadioButton.CanFocus = true;
		this.rouletteRadioButton.Name = "rouletteRadioButton";
		this.rouletteRadioButton.DrawIndicator = true;
		this.rouletteRadioButton.UseUnderline = true;
		this.rouletteRadioButton.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.fixed2.Add (this.rouletteRadioButton);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.rouletteRadioButton]));
		w18.X = 526;
		w18.Y = 161;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.tournamentRadioButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Tournament"));
		this.tournamentRadioButton.CanFocus = true;
		this.tournamentRadioButton.Name = "tournamentRadioButton";
		this.tournamentRadioButton.DrawIndicator = true;
		this.tournamentRadioButton.UseUnderline = true;
		this.tournamentRadioButton.Group = this.rouletteRadioButton.Group;
		this.fixed2.Add (this.tournamentRadioButton);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.tournamentRadioButton]));
		w19.X = 526;
		w19.Y = 135;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.elitistRadioButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Elitist"));
		this.elitistRadioButton.CanDefault = true;
		this.elitistRadioButton.CanFocus = true;
		this.elitistRadioButton.Name = "elitistRadioButton";
		this.elitistRadioButton.DrawIndicator = true;
		this.elitistRadioButton.UseUnderline = true;
		this.elitistRadioButton.Group = this.rouletteRadioButton.Group;
		this.fixed2.Add (this.elitistRadioButton);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.elitistRadioButton]));
		w20.X = 526;
		w20.Y = 109;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.image6 = new global::Gtk.Image ();
		this.image6.Name = "image6";
		this.fixed2.Add (this.image6);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.image6]));
		w21.X = 60;
		w21.Y = 19;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Mutation Occurance: ");
		this.fixed2.Add (this.label9);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label9]));
		w22.X = 584;
		w22.Y = 274;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Elites Percentage: ");
		this.fixed2.Add (this.label5);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label5]));
		w23.X = 584;
		w23.Y = 238;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Gene Mut. Chance: ");
		this.fixed2.Add (this.label7);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.label7]));
		w24.X = 584;
		w24.Y = 308;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.elitesPercentageTextBox = new global::Gtk.Entry ();
		this.elitesPercentageTextBox.WidthRequest = 60;
		this.elitesPercentageTextBox.CanFocus = true;
		this.elitesPercentageTextBox.Name = "elitesPercentageTextBox";
		this.elitesPercentageTextBox.Text = global::Mono.Unix.Catalog.GetString ("50");
		this.elitesPercentageTextBox.IsEditable = true;
		this.elitesPercentageTextBox.InvisibleChar = '●';
		this.fixed2.Add (this.elitesPercentageTextBox);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.elitesPercentageTextBox]));
		w25.X = 721;
		w25.Y = 233;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.mutationOccuranceTextBox = new global::Gtk.Entry ();
		this.mutationOccuranceTextBox.WidthRequest = 60;
		this.mutationOccuranceTextBox.CanFocus = true;
		this.mutationOccuranceTextBox.Name = "mutationOccuranceTextBox";
		this.mutationOccuranceTextBox.Text = global::Mono.Unix.Catalog.GetString ("10");
		this.mutationOccuranceTextBox.IsEditable = true;
		this.mutationOccuranceTextBox.InvisibleChar = '●';
		this.fixed2.Add (this.mutationOccuranceTextBox);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.mutationOccuranceTextBox]));
		w26.X = 721;
		w26.Y = 267;
		// Container child fixed2.Gtk.Fixed+FixedChild
		this.mutationPercentageTextBox = new global::Gtk.Entry ();
		this.mutationPercentageTextBox.WidthRequest = 60;
		this.mutationPercentageTextBox.CanFocus = true;
		this.mutationPercentageTextBox.Name = "mutationPercentageTextBox";
		this.mutationPercentageTextBox.Text = global::Mono.Unix.Catalog.GetString ("30");
		this.mutationPercentageTextBox.IsEditable = true;
		this.mutationPercentageTextBox.InvisibleChar = '●';
		this.fixed2.Add (this.mutationPercentageTextBox);
		global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed2 [this.mutationPercentageTextBox]));
		w27.X = 721;
		w27.Y = 303;
		this.vbox1.Add (this.fixed2);
		global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.fixed2]));
		w28.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 792;
		this.DefaultHeight = 396;
		this.elitistRadioButton.HasDefault = true;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.AboutMenuItem.Activated += new global::System.EventHandler (this.OnAboutMenuItemActivated);
		this.dialogQuestionAction.Activated += new global::System.EventHandler (this.OnDialogQuestionActionActivated);
		this.ExitMenuItem.Activated += new global::System.EventHandler (this.OnExitMenuItemActivated);
		this.CacheParametersAction.Activated += new global::System.EventHandler (this.OnCacheParametersMenuItemActivated);
		this.BpredParametersAction.Activated += new global::System.EventHandler (this.OnBpredParametersMenuItemActivated);
		this.OutorderParametersAction.Activated += new global::System.EventHandler (this.OnParametersMenuItemActivated);
		this.button1.Clicked += new global::System.EventHandler (this.TestComandaTerminal);
		this.rouletteRadioButton.Toggled += new global::System.EventHandler (this.OnRadiobutton1Toggled);
		this.tournamentRadioButton.Toggled += new global::System.EventHandler (this.OnRadiobutton1Toggled);
		this.elitistRadioButton.Toggled += new global::System.EventHandler (this.OnRadiobutton1Toggled);
	}
}
