
// This file has been generated by the GUI designer. Do not modify.
namespace Simoutorder
{
	public partial class CacheForm
	{
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Button SaveButton;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.Entry CacheDl1TextBox;
		
		private global::Gtk.Entry CacheDl1NsetsTextBox;
		
		private global::Gtk.Entry CacheDl1BsizeTextBox;
		
		private global::Gtk.Entry CacheDl1AssocTextBox;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.Entry CacheDl1ReplTextBox;
		
		private global::Gtk.Label label14;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label label15;
		
		private global::Gtk.Label label16;
		
		private global::Gtk.Label label17;
		
		private global::Gtk.Label label18;
		
		private global::Gtk.Label label19;
		
		private global::Gtk.Entry CacheIl1TextBox;
		
		private global::Gtk.Entry CacheIl1NsetsTextBox;
		
		private global::Gtk.Entry CacheIl1ReplTextBox;
		
		private global::Gtk.Entry CacheIl1AssocTextBox;
		
		private global::Gtk.Entry CacheIl1BsizeTextBox;
		
		private global::Gtk.Entry CacheTlbDataTextBox;
		
		private global::Gtk.Entry CacheTlbDataNsetsTextBox;
		
		private global::Gtk.Entry CacheTlbDataBsizeTextBox;
		
		private global::Gtk.Entry CacheTlbDataAssocTextBox;
		
		private global::Gtk.Entry CacheTlbDataReplTextBox;
		
		private global::Gtk.Label label24;
		
		private global::Gtk.Label label23;
		
		private global::Gtk.Label label22;
		
		private global::Gtk.Label label21;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Label label20;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Entry CacheDl2TextBox;
		
		private global::Gtk.Entry CacheIl2TextBox;
		
		private global::Gtk.Entry CacheTlbInstructionTextBox;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.CheckButton CacheIcompressCheckBox;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.CheckButton CacheFlushCheckBox;
		
		private global::Gtk.Label label25;
		
		private global::Gtk.Entry CacheDl2NsetsTextBox;
		
		private global::Gtk.Entry CacheDl2BsizeTextBox;
		
		private global::Gtk.Entry CacheDl2AssocTextBox;
		
		private global::Gtk.Entry CacheDl2ReplTextBox;
		
		private global::Gtk.Entry CacheIl2NsetsTextBox;
		
		private global::Gtk.Entry CacheIl2BsizeTextBox;
		
		private global::Gtk.Entry CacheIl2AssocTextBox;
		
		private global::Gtk.Entry CacheIl2ReplTextBox;
		
		private global::Gtk.Entry CacheTlbInstructionNsetsTextBox;
		
		private global::Gtk.Entry CacheTlbInstructionBsizeTextBox;
		
		private global::Gtk.Entry CacheTlbInstructionAssocTextBox;
		
		private global::Gtk.Entry CacheTlbInstructionReplTextBox;
		
		private global::Gtk.Label label26;
		
		private global::Gtk.Label label27;
		
		private global::Gtk.Label label28;
		
		private global::Gtk.Label label29;
		
		private global::Gtk.Label label34;
		
		private global::Gtk.Label label33;
		
		private global::Gtk.Label label32;
		
		private global::Gtk.Label label31;
		
		private global::Gtk.Label label30;
		
		private global::Gtk.Label label39;
		
		private global::Gtk.Label label38;
		
		private global::Gtk.Label label37;
		
		private global::Gtk.Label label36;
		
		private global::Gtk.Label label35;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Simoutorder.CacheForm
			this.Name = "Simoutorder.CacheForm";
			this.Title = global::Mono.Unix.Catalog.GetString ("Cache Parameters");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child Simoutorder.CacheForm.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Parametrii simulatorului de cache-uri:");
			this.fixed1.Add (this.label1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
			w1.X = 8;
			w1.Y = 6;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Cache:Dl1");
			this.fixed1.Add (this.label2);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
			w2.X = 13;
			w2.Y = 32;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.SaveButton = new global::Gtk.Button ();
			this.SaveButton.CanFocus = true;
			this.SaveButton.Name = "SaveButton";
			this.SaveButton.UseUnderline = true;
			this.SaveButton.Label = global::Mono.Unix.Catalog.GetString ("Salveaza");
			this.fixed1.Add (this.SaveButton);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.SaveButton]));
			w3.X = 733;
			w3.Y = 452;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label10 = new global::Gtk.Label ();
			global::Gtk.Tooltips w4 = new Gtk.Tooltips ();
			w4.SetTip (this.label10, "numele cache-ului, trebuie sa fie unic", "numele cache-ului, trebuie sa fie unic");
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("<name>");
			this.fixed1.Add (this.label10);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label10]));
			w5.X = 25;
			w5.Y = 60;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label11 = new global::Gtk.Label ();
			w4.SetTip (this.label11, "numarul de seturi din cache", "numarul de seturi din cache");
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("<nsets>");
			this.fixed1.Add (this.label11);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label11]));
			w6.X = 25;
			w6.Y = 89;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label12 = new global::Gtk.Label ();
			w4.SetTip (this.label12, "dimensiunea blocului", "dimensiunea blocului");
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("<bsize>");
			this.fixed1.Add (this.label12);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label12]));
			w7.X = 25;
			w7.Y = 119;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheDl1TextBox = new global::Gtk.Entry ();
			this.CacheDl1TextBox.CanFocus = true;
			this.CacheDl1TextBox.Name = "CacheDl1TextBox";
			this.CacheDl1TextBox.Text = global::Mono.Unix.Catalog.GetString ("dl1");
			this.CacheDl1TextBox.IsEditable = true;
			this.CacheDl1TextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheDl1TextBox);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheDl1TextBox]));
			w8.X = 90;
			w8.Y = 55;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheDl1NsetsTextBox = new global::Gtk.Entry ();
			this.CacheDl1NsetsTextBox.CanFocus = true;
			this.CacheDl1NsetsTextBox.Name = "CacheDl1NsetsTextBox";
			this.CacheDl1NsetsTextBox.Text = global::Mono.Unix.Catalog.GetString ("256");
			this.CacheDl1NsetsTextBox.IsEditable = true;
			this.CacheDl1NsetsTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheDl1NsetsTextBox);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheDl1NsetsTextBox]));
			w9.X = 90;
			w9.Y = 86;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheDl1BsizeTextBox = new global::Gtk.Entry ();
			this.CacheDl1BsizeTextBox.CanFocus = true;
			this.CacheDl1BsizeTextBox.Name = "CacheDl1BsizeTextBox";
			this.CacheDl1BsizeTextBox.Text = global::Mono.Unix.Catalog.GetString ("32");
			this.CacheDl1BsizeTextBox.IsEditable = true;
			this.CacheDl1BsizeTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheDl1BsizeTextBox);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheDl1BsizeTextBox]));
			w10.X = 90;
			w10.Y = 116;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheDl1AssocTextBox = new global::Gtk.Entry ();
			this.CacheDl1AssocTextBox.CanFocus = true;
			this.CacheDl1AssocTextBox.Name = "CacheDl1AssocTextBox";
			this.CacheDl1AssocTextBox.Text = global::Mono.Unix.Catalog.GetString ("1");
			this.CacheDl1AssocTextBox.IsEditable = true;
			this.CacheDl1AssocTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheDl1AssocTextBox);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheDl1AssocTextBox]));
			w11.X = 90;
			w11.Y = 149;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label13 = new global::Gtk.Label ();
			w4.SetTip (this.label13, "asociativitatea cache-ului (putere a lui 2)", "asociativitatea cache-ului (putere a lui 2)");
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("<assoc>");
			this.fixed1.Add (this.label13);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label13]));
			w12.X = 25;
			w12.Y = 150;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheDl1ReplTextBox = new global::Gtk.Entry ();
			this.CacheDl1ReplTextBox.CanFocus = true;
			this.CacheDl1ReplTextBox.Name = "CacheDl1ReplTextBox";
			this.CacheDl1ReplTextBox.Text = global::Mono.Unix.Catalog.GetString ("l");
			this.CacheDl1ReplTextBox.IsEditable = true;
			this.CacheDl1ReplTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheDl1ReplTextBox);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheDl1ReplTextBox]));
			w13.X = 90;
			w13.Y = 181;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label14 = new global::Gtk.Label ();
			w4.SetTip (this.label14, "politica de inlocuire a blocurilor din cache ( l | f | r ), l = LRU, f = FIFO, r = random", "politica de inlocuire a blocurilor din cache ( l | f | r ), l = LRU, f = FIFO, r = random");
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("<repl>");
			this.fixed1.Add (this.label14);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label14]));
			w14.X = 26;
			w14.Y = 183;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Cache:Il1");
			this.fixed1.Add (this.label4);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
			w15.X = 282;
			w15.Y = 31;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label15 = new global::Gtk.Label ();
			w4.SetTip (this.label15, "numele cache-ului, trebuie sa fie unic", "numele cache-ului, trebuie sa fie unic");
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("<name>");
			this.fixed1.Add (this.label15);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label15]));
			w16.X = 299;
			w16.Y = 58;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label16 = new global::Gtk.Label ();
			w4.SetTip (this.label16, "numarul de seturi din cache", "numarul de seturi din cache");
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("<nsets>");
			this.fixed1.Add (this.label16);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label16]));
			w17.X = 299;
			w17.Y = 87;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label17 = new global::Gtk.Label ();
			w4.SetTip (this.label17, "dimensiunea blocului", "dimensiunea blocului");
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("<bsize>");
			this.fixed1.Add (this.label17);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label17]));
			w18.X = 299;
			w18.Y = 117;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label18 = new global::Gtk.Label ();
			w4.SetTip (this.label18, "asociativitatea cache-ului (putere a lui 2)", "asociativitatea cache-ului (putere a lui 2)");
			this.label18.Name = "label18";
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("<assoc>");
			this.fixed1.Add (this.label18);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label18]));
			w19.X = 299;
			w19.Y = 150;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label19 = new global::Gtk.Label ();
			w4.SetTip (this.label19, "politica de inlocuire a blocurilor din cache ( l | f | r ), l = LRU, f = FIFO, r = random", "politica de inlocuire a blocurilor din cache ( l | f | r ), l = LRU, f = FIFO, r = random");
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("<repl>");
			this.fixed1.Add (this.label19);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label19]));
			w20.X = 300;
			w20.Y = 181;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheIl1TextBox = new global::Gtk.Entry ();
			this.CacheIl1TextBox.CanFocus = true;
			this.CacheIl1TextBox.Name = "CacheIl1TextBox";
			this.CacheIl1TextBox.Text = global::Mono.Unix.Catalog.GetString ("il1");
			this.CacheIl1TextBox.IsEditable = true;
			this.CacheIl1TextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheIl1TextBox);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheIl1TextBox]));
			w21.X = 365;
			w21.Y = 54;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheIl1NsetsTextBox = new global::Gtk.Entry ();
			this.CacheIl1NsetsTextBox.CanFocus = true;
			this.CacheIl1NsetsTextBox.Name = "CacheIl1NsetsTextBox";
			this.CacheIl1NsetsTextBox.Text = global::Mono.Unix.Catalog.GetString ("256");
			this.CacheIl1NsetsTextBox.IsEditable = true;
			this.CacheIl1NsetsTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheIl1NsetsTextBox);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheIl1NsetsTextBox]));
			w22.X = 365;
			w22.Y = 84;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheIl1ReplTextBox = new global::Gtk.Entry ();
			this.CacheIl1ReplTextBox.CanFocus = true;
			this.CacheIl1ReplTextBox.Name = "CacheIl1ReplTextBox";
			this.CacheIl1ReplTextBox.Text = global::Mono.Unix.Catalog.GetString ("l");
			this.CacheIl1ReplTextBox.IsEditable = true;
			this.CacheIl1ReplTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheIl1ReplTextBox);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheIl1ReplTextBox]));
			w23.X = 364;
			w23.Y = 180;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheIl1AssocTextBox = new global::Gtk.Entry ();
			this.CacheIl1AssocTextBox.CanFocus = true;
			this.CacheIl1AssocTextBox.Name = "CacheIl1AssocTextBox";
			this.CacheIl1AssocTextBox.Text = global::Mono.Unix.Catalog.GetString ("1");
			this.CacheIl1AssocTextBox.IsEditable = true;
			this.CacheIl1AssocTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheIl1AssocTextBox);
			global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheIl1AssocTextBox]));
			w24.X = 364;
			w24.Y = 150;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheIl1BsizeTextBox = new global::Gtk.Entry ();
			this.CacheIl1BsizeTextBox.CanFocus = true;
			this.CacheIl1BsizeTextBox.Name = "CacheIl1BsizeTextBox";
			this.CacheIl1BsizeTextBox.Text = global::Mono.Unix.Catalog.GetString ("32");
			this.CacheIl1BsizeTextBox.IsEditable = true;
			this.CacheIl1BsizeTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheIl1BsizeTextBox);
			global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheIl1BsizeTextBox]));
			w25.X = 364;
			w25.Y = 118;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheTlbDataTextBox = new global::Gtk.Entry ();
			this.CacheTlbDataTextBox.CanFocus = true;
			this.CacheTlbDataTextBox.Name = "CacheTlbDataTextBox";
			this.CacheTlbDataTextBox.Text = global::Mono.Unix.Catalog.GetString ("dtlb");
			this.CacheTlbDataTextBox.IsEditable = true;
			this.CacheTlbDataTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheTlbDataTextBox);
			global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheTlbDataTextBox]));
			w26.X = 639;
			w26.Y = 54;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheTlbDataNsetsTextBox = new global::Gtk.Entry ();
			this.CacheTlbDataNsetsTextBox.CanFocus = true;
			this.CacheTlbDataNsetsTextBox.Name = "CacheTlbDataNsetsTextBox";
			this.CacheTlbDataNsetsTextBox.Text = global::Mono.Unix.Catalog.GetString ("32");
			this.CacheTlbDataNsetsTextBox.IsEditable = true;
			this.CacheTlbDataNsetsTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheTlbDataNsetsTextBox);
			global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheTlbDataNsetsTextBox]));
			w27.X = 639;
			w27.Y = 86;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheTlbDataBsizeTextBox = new global::Gtk.Entry ();
			this.CacheTlbDataBsizeTextBox.CanFocus = true;
			this.CacheTlbDataBsizeTextBox.Name = "CacheTlbDataBsizeTextBox";
			this.CacheTlbDataBsizeTextBox.Text = global::Mono.Unix.Catalog.GetString ("4096");
			this.CacheTlbDataBsizeTextBox.IsEditable = true;
			this.CacheTlbDataBsizeTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheTlbDataBsizeTextBox);
			global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheTlbDataBsizeTextBox]));
			w28.X = 639;
			w28.Y = 118;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheTlbDataAssocTextBox = new global::Gtk.Entry ();
			this.CacheTlbDataAssocTextBox.CanFocus = true;
			this.CacheTlbDataAssocTextBox.Name = "CacheTlbDataAssocTextBox";
			this.CacheTlbDataAssocTextBox.Text = global::Mono.Unix.Catalog.GetString ("4");
			this.CacheTlbDataAssocTextBox.IsEditable = true;
			this.CacheTlbDataAssocTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheTlbDataAssocTextBox);
			global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheTlbDataAssocTextBox]));
			w29.X = 639;
			w29.Y = 149;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheTlbDataReplTextBox = new global::Gtk.Entry ();
			this.CacheTlbDataReplTextBox.CanFocus = true;
			this.CacheTlbDataReplTextBox.Name = "CacheTlbDataReplTextBox";
			this.CacheTlbDataReplTextBox.Text = global::Mono.Unix.Catalog.GetString ("l");
			this.CacheTlbDataReplTextBox.IsEditable = true;
			this.CacheTlbDataReplTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheTlbDataReplTextBox);
			global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheTlbDataReplTextBox]));
			w30.X = 639;
			w30.Y = 180;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label24 = new global::Gtk.Label ();
			w4.SetTip (this.label24, "politica de inlocuire a blocurilor din cache ( l | f | r ), l = LRU, f = FIFO, r = random", "politica de inlocuire a blocurilor din cache ( l | f | r ), l = LRU, f = FIFO, r = random");
			this.label24.Name = "label24";
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString ("<repl>");
			this.fixed1.Add (this.label24);
			global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label24]));
			w31.X = 570;
			w31.Y = 181;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label23 = new global::Gtk.Label ();
			w4.SetTip (this.label23, "asociativitatea cache-ului (putere a lui 2)", "asociativitatea cache-ului (putere a lui 2)");
			this.label23.Name = "label23";
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString ("<assoc>");
			this.fixed1.Add (this.label23);
			global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label23]));
			w32.X = 570;
			w32.Y = 152;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label22 = new global::Gtk.Label ();
			w4.SetTip (this.label22, "dimensiunea blocului", "dimensiunea blocului");
			this.label22.Name = "label22";
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("<bsize>");
			this.fixed1.Add (this.label22);
			global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label22]));
			w33.X = 570;
			w33.Y = 121;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label21 = new global::Gtk.Label ();
			w4.SetTip (this.label21, "numarul de seturi din cache", "numarul de seturi din cache");
			this.label21.Name = "label21";
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("<nsets>");
			this.fixed1.Add (this.label21);
			global::Gtk.Fixed.FixedChild w34 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label21]));
			w34.X = 570;
			w34.Y = 89;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Tlb:Dtlb");
			this.fixed1.Add (this.label6);
			global::Gtk.Fixed.FixedChild w35 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label6]));
			w35.X = 555;
			w35.Y = 29;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label20 = new global::Gtk.Label ();
			w4.SetTip (this.label20, "numele cache-ului, trebuie sa fie unic", "numele cache-ului, trebuie sa fie unic");
			this.label20.Name = "label20";
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("<name>");
			this.fixed1.Add (this.label20);
			global::Gtk.Fixed.FixedChild w36 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label20]));
			w36.X = 571;
			w36.Y = 58;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Cache:Dl2");
			this.fixed1.Add (this.label3);
			global::Gtk.Fixed.FixedChild w37 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
			w37.X = 14;
			w37.Y = 223;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Cache:Il2");
			this.fixed1.Add (this.label5);
			global::Gtk.Fixed.FixedChild w38 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label5]));
			w38.X = 283;
			w38.Y = 219;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Tlb:Itlb");
			this.fixed1.Add (this.label7);
			global::Gtk.Fixed.FixedChild w39 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label7]));
			w39.X = 557;
			w39.Y = 218;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheDl2TextBox = new global::Gtk.Entry ();
			this.CacheDl2TextBox.CanFocus = true;
			this.CacheDl2TextBox.Name = "CacheDl2TextBox";
			this.CacheDl2TextBox.Text = global::Mono.Unix.Catalog.GetString ("dl2");
			this.CacheDl2TextBox.IsEditable = true;
			this.CacheDl2TextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheDl2TextBox);
			global::Gtk.Fixed.FixedChild w40 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheDl2TextBox]));
			w40.X = 90;
			w40.Y = 244;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheIl2TextBox = new global::Gtk.Entry ();
			this.CacheIl2TextBox.CanFocus = true;
			this.CacheIl2TextBox.Name = "CacheIl2TextBox";
			this.CacheIl2TextBox.Text = global::Mono.Unix.Catalog.GetString ("il2");
			this.CacheIl2TextBox.IsEditable = true;
			this.CacheIl2TextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheIl2TextBox);
			global::Gtk.Fixed.FixedChild w41 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheIl2TextBox]));
			w41.X = 364;
			w41.Y = 244;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheTlbInstructionTextBox = new global::Gtk.Entry ();
			this.CacheTlbInstructionTextBox.CanFocus = true;
			this.CacheTlbInstructionTextBox.Name = "CacheTlbInstructionTextBox";
			this.CacheTlbInstructionTextBox.Text = global::Mono.Unix.Catalog.GetString ("itlb");
			this.CacheTlbInstructionTextBox.IsEditable = true;
			this.CacheTlbInstructionTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheTlbInstructionTextBox);
			global::Gtk.Fixed.FixedChild w42 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheTlbInstructionTextBox]));
			w42.X = 639;
			w42.Y = 244;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Icompress");
			this.fixed1.Add (this.label9);
			global::Gtk.Fixed.FixedChild w43 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label9]));
			w43.X = 22;
			w43.Y = 454;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheIcompressCheckBox = new global::Gtk.CheckButton ();
			this.CacheIcompressCheckBox.CanFocus = true;
			this.CacheIcompressCheckBox.Name = "CacheIcompressCheckBox";
			this.CacheIcompressCheckBox.Label = global::Mono.Unix.Catalog.GetString ("Activate");
			this.CacheIcompressCheckBox.DrawIndicator = true;
			this.CacheIcompressCheckBox.UseUnderline = true;
			this.fixed1.Add (this.CacheIcompressCheckBox);
			global::Gtk.Fixed.FixedChild w44 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheIcompressCheckBox]));
			w44.X = 121;
			w44.Y = 451;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Flush");
			this.fixed1.Add (this.label8);
			global::Gtk.Fixed.FixedChild w45 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label8]));
			w45.X = 22;
			w45.Y = 423;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheFlushCheckBox = new global::Gtk.CheckButton ();
			this.CacheFlushCheckBox.CanFocus = true;
			this.CacheFlushCheckBox.Name = "CacheFlushCheckBox";
			this.CacheFlushCheckBox.Label = global::Mono.Unix.Catalog.GetString ("Activate");
			this.CacheFlushCheckBox.DrawIndicator = true;
			this.CacheFlushCheckBox.UseUnderline = true;
			this.fixed1.Add (this.CacheFlushCheckBox);
			global::Gtk.Fixed.FixedChild w46 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheFlushCheckBox]));
			w46.X = 121;
			w46.Y = 418;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label25 = new global::Gtk.Label ();
			w4.SetTip (this.label25, "numele cache-ului, trebuie sa fie unic", "numele cache-ului, trebuie sa fie unic");
			this.label25.Name = "label25";
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString ("<name>");
			this.fixed1.Add (this.label25);
			global::Gtk.Fixed.FixedChild w47 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label25]));
			w47.X = 27;
			w47.Y = 246;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheDl2NsetsTextBox = new global::Gtk.Entry ();
			this.CacheDl2NsetsTextBox.CanFocus = true;
			this.CacheDl2NsetsTextBox.Name = "CacheDl2NsetsTextBox";
			this.CacheDl2NsetsTextBox.Text = global::Mono.Unix.Catalog.GetString ("256");
			this.CacheDl2NsetsTextBox.IsEditable = true;
			this.CacheDl2NsetsTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheDl2NsetsTextBox);
			global::Gtk.Fixed.FixedChild w48 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheDl2NsetsTextBox]));
			w48.X = 90;
			w48.Y = 274;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheDl2BsizeTextBox = new global::Gtk.Entry ();
			this.CacheDl2BsizeTextBox.CanFocus = true;
			this.CacheDl2BsizeTextBox.Name = "CacheDl2BsizeTextBox";
			this.CacheDl2BsizeTextBox.Text = global::Mono.Unix.Catalog.GetString ("32");
			this.CacheDl2BsizeTextBox.IsEditable = true;
			this.CacheDl2BsizeTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheDl2BsizeTextBox);
			global::Gtk.Fixed.FixedChild w49 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheDl2BsizeTextBox]));
			w49.X = 90;
			w49.Y = 304;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheDl2AssocTextBox = new global::Gtk.Entry ();
			this.CacheDl2AssocTextBox.CanFocus = true;
			this.CacheDl2AssocTextBox.Name = "CacheDl2AssocTextBox";
			this.CacheDl2AssocTextBox.Text = global::Mono.Unix.Catalog.GetString ("1");
			this.CacheDl2AssocTextBox.IsEditable = true;
			this.CacheDl2AssocTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheDl2AssocTextBox);
			global::Gtk.Fixed.FixedChild w50 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheDl2AssocTextBox]));
			w50.X = 90;
			w50.Y = 335;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheDl2ReplTextBox = new global::Gtk.Entry ();
			this.CacheDl2ReplTextBox.CanFocus = true;
			this.CacheDl2ReplTextBox.Name = "CacheDl2ReplTextBox";
			this.CacheDl2ReplTextBox.Text = global::Mono.Unix.Catalog.GetString ("l");
			this.CacheDl2ReplTextBox.IsEditable = true;
			this.CacheDl2ReplTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheDl2ReplTextBox);
			global::Gtk.Fixed.FixedChild w51 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheDl2ReplTextBox]));
			w51.X = 90;
			w51.Y = 367;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheIl2NsetsTextBox = new global::Gtk.Entry ();
			this.CacheIl2NsetsTextBox.CanFocus = true;
			this.CacheIl2NsetsTextBox.Name = "CacheIl2NsetsTextBox";
			this.CacheIl2NsetsTextBox.Text = global::Mono.Unix.Catalog.GetString ("256");
			this.CacheIl2NsetsTextBox.IsEditable = true;
			this.CacheIl2NsetsTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheIl2NsetsTextBox);
			global::Gtk.Fixed.FixedChild w52 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheIl2NsetsTextBox]));
			w52.X = 364;
			w52.Y = 274;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheIl2BsizeTextBox = new global::Gtk.Entry ();
			this.CacheIl2BsizeTextBox.CanFocus = true;
			this.CacheIl2BsizeTextBox.Name = "CacheIl2BsizeTextBox";
			this.CacheIl2BsizeTextBox.Text = global::Mono.Unix.Catalog.GetString ("32");
			this.CacheIl2BsizeTextBox.IsEditable = true;
			this.CacheIl2BsizeTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheIl2BsizeTextBox);
			global::Gtk.Fixed.FixedChild w53 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheIl2BsizeTextBox]));
			w53.X = 364;
			w53.Y = 304;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheIl2AssocTextBox = new global::Gtk.Entry ();
			this.CacheIl2AssocTextBox.CanFocus = true;
			this.CacheIl2AssocTextBox.Name = "CacheIl2AssocTextBox";
			this.CacheIl2AssocTextBox.Text = global::Mono.Unix.Catalog.GetString ("1");
			this.CacheIl2AssocTextBox.IsEditable = true;
			this.CacheIl2AssocTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheIl2AssocTextBox);
			global::Gtk.Fixed.FixedChild w54 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheIl2AssocTextBox]));
			w54.X = 364;
			w54.Y = 334;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheIl2ReplTextBox = new global::Gtk.Entry ();
			this.CacheIl2ReplTextBox.CanFocus = true;
			this.CacheIl2ReplTextBox.Name = "CacheIl2ReplTextBox";
			this.CacheIl2ReplTextBox.Text = global::Mono.Unix.Catalog.GetString ("l");
			this.CacheIl2ReplTextBox.IsEditable = true;
			this.CacheIl2ReplTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheIl2ReplTextBox);
			global::Gtk.Fixed.FixedChild w55 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheIl2ReplTextBox]));
			w55.X = 364;
			w55.Y = 367;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheTlbInstructionNsetsTextBox = new global::Gtk.Entry ();
			this.CacheTlbInstructionNsetsTextBox.CanFocus = true;
			this.CacheTlbInstructionNsetsTextBox.Name = "CacheTlbInstructionNsetsTextBox";
			this.CacheTlbInstructionNsetsTextBox.Text = global::Mono.Unix.Catalog.GetString ("16");
			this.CacheTlbInstructionNsetsTextBox.IsEditable = true;
			this.CacheTlbInstructionNsetsTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheTlbInstructionNsetsTextBox);
			global::Gtk.Fixed.FixedChild w56 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheTlbInstructionNsetsTextBox]));
			w56.X = 639;
			w56.Y = 275;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheTlbInstructionBsizeTextBox = new global::Gtk.Entry ();
			this.CacheTlbInstructionBsizeTextBox.CanFocus = true;
			this.CacheTlbInstructionBsizeTextBox.Name = "CacheTlbInstructionBsizeTextBox";
			this.CacheTlbInstructionBsizeTextBox.Text = global::Mono.Unix.Catalog.GetString ("4096");
			this.CacheTlbInstructionBsizeTextBox.IsEditable = true;
			this.CacheTlbInstructionBsizeTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheTlbInstructionBsizeTextBox);
			global::Gtk.Fixed.FixedChild w57 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheTlbInstructionBsizeTextBox]));
			w57.X = 639;
			w57.Y = 305;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheTlbInstructionAssocTextBox = new global::Gtk.Entry ();
			this.CacheTlbInstructionAssocTextBox.CanFocus = true;
			this.CacheTlbInstructionAssocTextBox.Name = "CacheTlbInstructionAssocTextBox";
			this.CacheTlbInstructionAssocTextBox.Text = global::Mono.Unix.Catalog.GetString ("4");
			this.CacheTlbInstructionAssocTextBox.IsEditable = true;
			this.CacheTlbInstructionAssocTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheTlbInstructionAssocTextBox);
			global::Gtk.Fixed.FixedChild w58 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheTlbInstructionAssocTextBox]));
			w58.X = 639;
			w58.Y = 335;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.CacheTlbInstructionReplTextBox = new global::Gtk.Entry ();
			this.CacheTlbInstructionReplTextBox.CanFocus = true;
			this.CacheTlbInstructionReplTextBox.Name = "CacheTlbInstructionReplTextBox";
			this.CacheTlbInstructionReplTextBox.Text = global::Mono.Unix.Catalog.GetString ("l");
			this.CacheTlbInstructionReplTextBox.IsEditable = true;
			this.CacheTlbInstructionReplTextBox.InvisibleChar = '•';
			this.fixed1.Add (this.CacheTlbInstructionReplTextBox);
			global::Gtk.Fixed.FixedChild w59 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.CacheTlbInstructionReplTextBox]));
			w59.X = 639;
			w59.Y = 366;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label26 = new global::Gtk.Label ();
			w4.SetTip (this.label26, "numarul de seturi din cache", "numarul de seturi din cache");
			this.label26.Name = "label26";
			this.label26.LabelProp = global::Mono.Unix.Catalog.GetString ("<nsets>");
			this.fixed1.Add (this.label26);
			global::Gtk.Fixed.FixedChild w60 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label26]));
			w60.X = 28;
			w60.Y = 277;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label27 = new global::Gtk.Label ();
			w4.SetTip (this.label27, "dimensiunea blocului", "dimensiunea blocului");
			this.label27.Name = "label27";
			this.label27.LabelProp = global::Mono.Unix.Catalog.GetString ("<bsize>");
			this.fixed1.Add (this.label27);
			global::Gtk.Fixed.FixedChild w61 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label27]));
			w61.X = 28;
			w61.Y = 308;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label28 = new global::Gtk.Label ();
			w4.SetTip (this.label28, "asociativitatea cache-ului (putere a lui 2)", "asociativitatea cache-ului (putere a lui 2)");
			this.label28.Name = "label28";
			this.label28.LabelProp = global::Mono.Unix.Catalog.GetString ("<assoc>");
			this.fixed1.Add (this.label28);
			global::Gtk.Fixed.FixedChild w62 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label28]));
			w62.X = 28;
			w62.Y = 338;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label29 = new global::Gtk.Label ();
			w4.SetTip (this.label29, "politica de inlocuire a blocurilor din cache ( l | f | r ), l = LRU, f = FIFO, r = random", "politica de inlocuire a blocurilor din cache ( l | f | r ), l = LRU, f = FIFO, r = random");
			this.label29.Name = "label29";
			this.label29.LabelProp = global::Mono.Unix.Catalog.GetString ("<repl>");
			this.fixed1.Add (this.label29);
			global::Gtk.Fixed.FixedChild w63 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label29]));
			w63.X = 30;
			w63.Y = 370;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label34 = new global::Gtk.Label ();
			w4.SetTip (this.label34, "politica de inlocuire a blocurilor din cache ( l | f | r ), l = LRU, f = FIFO, r = random", "politica de inlocuire a blocurilor din cache ( l | f | r ), l = LRU, f = FIFO, r = random");
			this.label34.Name = "label34";
			this.label34.LabelProp = global::Mono.Unix.Catalog.GetString ("<repl>");
			this.fixed1.Add (this.label34);
			global::Gtk.Fixed.FixedChild w64 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label34]));
			w64.X = 304;
			w64.Y = 371;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label33 = new global::Gtk.Label ();
			w4.SetTip (this.label33, "asociativitatea cache-ului (putere a lui 2)", "asociativitatea cache-ului (putere a lui 2)");
			this.label33.Name = "label33";
			this.label33.LabelProp = global::Mono.Unix.Catalog.GetString ("<assoc>");
			this.fixed1.Add (this.label33);
			global::Gtk.Fixed.FixedChild w65 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label33]));
			w65.X = 304;
			w65.Y = 338;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label32 = new global::Gtk.Label ();
			w4.SetTip (this.label32, "dimensiunea blocului", "dimensiunea blocului");
			this.label32.Name = "label32";
			this.label32.LabelProp = global::Mono.Unix.Catalog.GetString ("<bsize>");
			this.fixed1.Add (this.label32);
			global::Gtk.Fixed.FixedChild w66 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label32]));
			w66.X = 304;
			w66.Y = 306;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label31 = new global::Gtk.Label ();
			w4.SetTip (this.label31, "numarul de seturi din cache", "numarul de seturi din cache");
			this.label31.Name = "label31";
			this.label31.LabelProp = global::Mono.Unix.Catalog.GetString ("<nsets>");
			this.fixed1.Add (this.label31);
			global::Gtk.Fixed.FixedChild w67 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label31]));
			w67.X = 304;
			w67.Y = 277;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label30 = new global::Gtk.Label ();
			w4.SetTip (this.label30, "numele cache-ului, trebuie sa fie unic", "numele cache-ului, trebuie sa fie unic");
			this.label30.Name = "label30";
			this.label30.LabelProp = global::Mono.Unix.Catalog.GetString ("<name>");
			this.fixed1.Add (this.label30);
			global::Gtk.Fixed.FixedChild w68 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label30]));
			w68.X = 304;
			w68.Y = 247;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label39 = new global::Gtk.Label ();
			w4.SetTip (this.label39, "politica de inlocuire a blocurilor din cache ( l | f | r ), l = LRU, f = FIFO, r = random", "politica de inlocuire a blocurilor din cache ( l | f | r ), l = LRU, f = FIFO, r = random");
			this.label39.Name = "label39";
			this.label39.LabelProp = global::Mono.Unix.Catalog.GetString ("<repl>");
			this.fixed1.Add (this.label39);
			global::Gtk.Fixed.FixedChild w69 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label39]));
			w69.X = 575;
			w69.Y = 369;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label38 = new global::Gtk.Label ();
			w4.SetTip (this.label38, "asociativitatea cache-ului (putere a lui 2)", "asociativitatea cache-ului (putere a lui 2)");
			this.label38.Name = "label38";
			this.label38.LabelProp = global::Mono.Unix.Catalog.GetString ("<assoc>");
			this.fixed1.Add (this.label38);
			global::Gtk.Fixed.FixedChild w70 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label38]));
			w70.X = 575;
			w70.Y = 339;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label37 = new global::Gtk.Label ();
			w4.SetTip (this.label37, "dimensiunea blocului", "dimensiunea blocului");
			this.label37.Name = "label37";
			this.label37.LabelProp = global::Mono.Unix.Catalog.GetString ("<bsize>");
			this.fixed1.Add (this.label37);
			global::Gtk.Fixed.FixedChild w71 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label37]));
			w71.X = 575;
			w71.Y = 309;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label36 = new global::Gtk.Label ();
			w4.SetTip (this.label36, "numarul de seturi din cache", "numarul de seturi din cache");
			this.label36.Name = "label36";
			this.label36.LabelProp = global::Mono.Unix.Catalog.GetString ("<nsets>");
			this.fixed1.Add (this.label36);
			global::Gtk.Fixed.FixedChild w72 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label36]));
			w72.X = 575;
			w72.Y = 279;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label35 = new global::Gtk.Label ();
			w4.SetTip (this.label35, "numele cache-ului, trebuie sa fie unic", "numele cache-ului, trebuie sa fie unic");
			this.label35.Name = "label35";
			this.label35.LabelProp = global::Mono.Unix.Catalog.GetString ("<name>");
			this.fixed1.Add (this.label35);
			global::Gtk.Fixed.FixedChild w73 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label35]));
			w73.X = 575;
			w73.Y = 248;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 814;
			this.DefaultHeight = 493;
			this.Show ();
			this.SaveButton.Clicked += new global::System.EventHandler (this.OnSaveButtonClicked);
		}
	}
}
