
// This file has been generated by the GUI designer. Do not modify.
namespace Simoutorder
{
	public partial class HelpForm
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Simoutorder.HelpForm
			this.Name = "Simoutorder.HelpForm";
			this.Title = global::Mono.Unix.Catalog.GetString ("HelpForm");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
