
// This file has been generated by the GUI designer. Do not modify.
namespace Simoutorder
{
	public partial class AboutForm
	{
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Image image85;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Simoutorder.AboutForm
			this.Name = "Simoutorder.AboutForm";
			this.Title = global::Mono.Unix.Catalog.GetString ("AboutForm");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Gravity = ((global::Gdk.Gravity)(5));
			// Container child Simoutorder.AboutForm.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Version: Beta");
			this.fixed1.Add (this.label5);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label5]));
			w1.X = 20;
			w1.Y = 89;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Student:");
			this.fixed1.Add (this.label6);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label6]));
			w2.X = 21;
			w2.Y = 118;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Elimelec Burghelea");
			this.fixed1.Add (this.label7);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label7]));
			w3.X = 32;
			w3.Y = 145;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Coordinator:");
			this.fixed1.Add (this.label9);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label9]));
			w4.X = 22;
			w4.Y = 205;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Prof. dr. ing. Adrian FLOREA");
			this.fixed1.Add (this.label10);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label10]));
			w5.X = 33;
			w5.Y = 235;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.image85 = new global::Gtk.Image ();
			this.image85.Name = "image85";
			this.fixed1.Add (this.image85);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.image85]));
			w6.X = 15;
			w6.Y = 17;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 696;
			this.DefaultHeight = 310;
			this.Show ();
		}
	}
}
