
// This file has been generated by the GUI designer. Do not modify.
namespace Simoutorder
{
	public partial class ParameterForm
	{
		private global::Gtk.Fixed MainContainer;
		
		private global::Gtk.Button SaveButton;
		
		private global::Gtk.Entry ResFpmultTextBox;
		
		private global::Gtk.Entry ResMemportsTextBox;
		
		private global::Gtk.Entry ResFpaluTextBox;
		
		private global::Gtk.Entry ResImultTextBox;
		
		private global::Gtk.Entry ResIaluTextBox;
		
		private global::Gtk.Entry LsqSizeTextBox;
		
		private global::Gtk.Entry RuuSizeTextBox;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.CheckButton IssueWrongpathCheckBox;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.CheckButton IssueInorderCheckBox;
		
		private global::Gtk.ComboBox IssueWidthComboBox;
		
		private global::Gtk.ComboBox DecodeWidthComboBox;
		
		private global::Gtk.Entry FetchmplatTextBox;
		
		private global::Gtk.ComboBox FetchifqSizeComboBox;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label mda;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.Label label14;
		
		private global::Gtk.Label label15;
		
		private global::Gtk.Label label16;
		
		private global::Gtk.Label label17;
		
		private global::Gtk.Entry Cachedl1latTextBox;
		
		private global::Gtk.Entry MemwidthTextBox;
		
		private global::Gtk.Entry TlblatTextBox;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Simoutorder.ParameterForm
			this.Name = "Simoutorder.ParameterForm";
			this.Title = global::Mono.Unix.Catalog.GetString ("Parameters");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child Simoutorder.ParameterForm.Gtk.Container+ContainerChild
			this.MainContainer = new global::Gtk.Fixed ();
			this.MainContainer.Name = "MainContainer";
			this.MainContainer.HasWindow = false;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.SaveButton = new global::Gtk.Button ();
			this.SaveButton.CanFocus = true;
			this.SaveButton.Name = "SaveButton";
			this.SaveButton.UseUnderline = true;
			this.SaveButton.Label = global::Mono.Unix.Catalog.GetString ("Salveaza");
			global::Gtk.Image w1 = new global::Gtk.Image ();
			w1.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Menu);
			this.SaveButton.Image = w1;
			this.MainContainer.Add (this.SaveButton);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.SaveButton]));
			w2.X = 731;
			w2.Y = 427;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.ResFpmultTextBox = new global::Gtk.Entry ();
			global::Gtk.Tooltips w3 = new Gtk.Tooltips ();
			w3.SetTip (this.ResFpmultTextBox, "specifica numarul unitatilor de\nînmultire/împartire în virgula mobila.", "specifica numarul unitatilor de\nînmultire/împartire în virgula mobila.");
			this.ResFpmultTextBox.WidthRequest = 50;
			this.ResFpmultTextBox.CanFocus = true;
			this.ResFpmultTextBox.Name = "ResFpmultTextBox";
			this.ResFpmultTextBox.Text = global::Mono.Unix.Catalog.GetString ("1");
			this.ResFpmultTextBox.IsEditable = true;
			this.ResFpmultTextBox.InvisibleChar = '●';
			this.MainContainer.Add (this.ResFpmultTextBox);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.ResFpmultTextBox]));
			w4.X = 163;
			w4.Y = 427;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.ResMemportsTextBox = new global::Gtk.Entry ();
			w3.SetTip (this.ResMemportsTextBox, "specifica numarul porturilor cache-ului de pe\nnivelul L1.", "specifica numarul porturilor cache-ului de pe\nnivelul L1.");
			this.ResMemportsTextBox.WidthRequest = 50;
			this.ResMemportsTextBox.CanFocus = true;
			this.ResMemportsTextBox.Name = "ResMemportsTextBox";
			this.ResMemportsTextBox.Text = global::Mono.Unix.Catalog.GetString ("2");
			this.ResMemportsTextBox.IsEditable = true;
			this.ResMemportsTextBox.InvisibleChar = '●';
			this.MainContainer.Add (this.ResMemportsTextBox);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.ResMemportsTextBox]));
			w5.X = 163;
			w5.Y = 368;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.ResFpaluTextBox = new global::Gtk.Entry ();
			w3.SetTip (this.ResFpaluTextBox, "specifica numarul unitatilor ALU în virgula\nmobila.", "specifica numarul unitatilor ALU în virgula\nmobila.");
			this.ResFpaluTextBox.WidthRequest = 50;
			this.ResFpaluTextBox.CanFocus = true;
			this.ResFpaluTextBox.Name = "ResFpaluTextBox";
			this.ResFpaluTextBox.Text = global::Mono.Unix.Catalog.GetString ("4");
			this.ResFpaluTextBox.IsEditable = true;
			this.ResFpaluTextBox.InvisibleChar = '●';
			this.MainContainer.Add (this.ResFpaluTextBox);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.ResFpaluTextBox]));
			w6.X = 163;
			w6.Y = 398;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.ResImultTextBox = new global::Gtk.Entry ();
			w3.SetTip (this.ResImultTextBox, "specifica numarul unitatilor de înmultire/împartire\nîntregi.", "specifica numarul unitatilor de înmultire/împartire\nîntregi.");
			this.ResImultTextBox.WidthRequest = 50;
			this.ResImultTextBox.CanFocus = true;
			this.ResImultTextBox.Name = "ResImultTextBox";
			this.ResImultTextBox.Text = global::Mono.Unix.Catalog.GetString ("1");
			this.ResImultTextBox.IsEditable = true;
			this.ResImultTextBox.InvisibleChar = '●';
			this.MainContainer.Add (this.ResImultTextBox);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.ResImultTextBox]));
			w7.X = 163;
			w7.Y = 338;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.ResIaluTextBox = new global::Gtk.Entry ();
			w3.SetTip (this.ResIaluTextBox, "pecifica numarul unitatilor ALU de numere\nîntregi.", "pecifica numarul unitatilor ALU de numere\nîntregi.");
			this.ResIaluTextBox.WidthRequest = 50;
			this.ResIaluTextBox.CanFocus = true;
			this.ResIaluTextBox.Name = "ResIaluTextBox";
			this.ResIaluTextBox.Text = global::Mono.Unix.Catalog.GetString ("4");
			this.ResIaluTextBox.IsEditable = true;
			this.ResIaluTextBox.InvisibleChar = '●';
			this.MainContainer.Add (this.ResIaluTextBox);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.ResIaluTextBox]));
			w8.X = 163;
			w8.Y = 308;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.LsqSizeTextBox = new global::Gtk.Entry ();
			w3.SetTip (this.LsqSizeTextBox, "capacitatea bufferului Load/Store (în instructiuni).", "capacitatea bufferului Load/Store (în instructiuni).");
			this.LsqSizeTextBox.WidthRequest = 50;
			this.LsqSizeTextBox.CanFocus = true;
			this.LsqSizeTextBox.Name = "LsqSizeTextBox";
			this.LsqSizeTextBox.Text = global::Mono.Unix.Catalog.GetString ("8");
			this.LsqSizeTextBox.IsEditable = true;
			this.LsqSizeTextBox.InvisibleChar = '●';
			this.MainContainer.Add (this.LsqSizeTextBox);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.LsqSizeTextBox]));
			w9.X = 163;
			w9.Y = 277;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.RuuSizeTextBox = new global::Gtk.Entry ();
			w3.SetTip (this.RuuSizeTextBox, "capacitatea unitatii RUU (în instructiuni). Implicit\nia valoarea 16.", "capacitatea unitatii RUU (în instructiuni). Implicit\nia valoarea 16.");
			this.RuuSizeTextBox.WidthRequest = 50;
			this.RuuSizeTextBox.CanFocus = true;
			this.RuuSizeTextBox.Name = "RuuSizeTextBox";
			this.RuuSizeTextBox.Text = global::Mono.Unix.Catalog.GetString ("16");
			this.RuuSizeTextBox.IsEditable = true;
			this.RuuSizeTextBox.InvisibleChar = '●';
			this.MainContainer.Add (this.RuuSizeTextBox);
			global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.RuuSizeTextBox]));
			w10.X = 163;
			w10.Y = 247;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.label13 = new global::Gtk.Label ();
			w3.SetTip (this.label13, "specifica numarul unitatilor de\nînmultire/împartire în virgula mobila.", "specifica numarul unitatilor de\nînmultire/împartire în virgula mobila.");
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Res:fpmult <num>");
			this.MainContainer.Add (this.label13);
			global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.label13]));
			w11.X = 10;
			w11.Y = 430;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.label12 = new global::Gtk.Label ();
			w3.SetTip (this.label12, "specifica numarul unitatilor ALU în virgula\nmobila.", "specifica numarul unitatilor ALU în virgula\nmobila.");
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Res:fpalu <num>");
			this.MainContainer.Add (this.label12);
			global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.label12]));
			w12.X = 10;
			w12.Y = 401;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.label11 = new global::Gtk.Label ();
			w3.SetTip (this.label11, "specifica numarul porturilor cache-ului de pe\nnivelul L1.", "specifica numarul porturilor cache-ului de pe\nnivelul L1.");
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Res:memports <num>");
			this.MainContainer.Add (this.label11);
			global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.label11]));
			w13.X = 10;
			w13.Y = 371;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.label10 = new global::Gtk.Label ();
			w3.SetTip (this.label10, "specifica numarul unitatilor de înmultire/împartire\nîntregi.", "specifica numarul unitatilor de înmultire/împartire\nîntregi.");
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Res:imult <num>");
			this.MainContainer.Add (this.label10);
			global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.label10]));
			w14.X = 10;
			w14.Y = 341;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.label9 = new global::Gtk.Label ();
			w3.SetTip (this.label9, "pecifica numarul unitatilor ALU de numere\nîntregi.", "pecifica numarul unitatilor ALU de numere\nîntregi.");
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Res:ialu <num>");
			this.MainContainer.Add (this.label9);
			global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.label9]));
			w15.X = 11;
			w15.Y = 311;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.label8 = new global::Gtk.Label ();
			w3.SetTip (this.label8, "capacitatea bufferului Load/Store (în instructiuni).", "capacitatea bufferului Load/Store (în instructiuni).");
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Lsq:size <insts>");
			this.MainContainer.Add (this.label8);
			global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.label8]));
			w16.X = 11;
			w16.Y = 280;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label ();
			w3.SetTip (this.label3, "capacitatea unitatii RUU (în instructiuni). Implicit\nia valoarea 16.", "capacitatea unitatii RUU (în instructiuni). Implicit\nia valoarea 16.");
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Ruu:size <insts>");
			this.MainContainer.Add (this.label3);
			global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.label3]));
			w17.X = 11;
			w17.Y = 248;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.label7 = new global::Gtk.Label ();
			w3.SetTip (this.label7, "permite expedierea spre executie a instructiunilor\ndupa o speculatie gresita.", "permite expedierea spre executie a instructiunilor\ndupa o speculatie gresita.");
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Issue:wrongpath");
			this.MainContainer.Add (this.label7);
			global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.label7]));
			w18.X = 12;
			w18.Y = 214;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.IssueWrongpathCheckBox = new global::Gtk.CheckButton ();
			w3.SetTip (this.IssueWrongpathCheckBox, "permite expedierea spre executie a instructiunilor\ndupa o speculatie gresita.", "permite expedierea spre executie a instructiunilor\ndupa o speculatie gresita.");
			this.IssueWrongpathCheckBox.CanFocus = true;
			this.IssueWrongpathCheckBox.Name = "IssueWrongpathCheckBox";
			this.IssueWrongpathCheckBox.Label = global::Mono.Unix.Catalog.GetString ("Issue Wrongpath");
			this.IssueWrongpathCheckBox.Active = true;
			this.IssueWrongpathCheckBox.DrawIndicator = true;
			this.IssueWrongpathCheckBox.UseUnderline = true;
			this.MainContainer.Add (this.IssueWrongpathCheckBox);
			global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.IssueWrongpathCheckBox]));
			w19.X = 162;
			w19.Y = 209;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.label6 = new global::Gtk.Label ();
			w3.SetTip (this.label6, "forteaza simulatorul sa lucreze in-order.", "forteaza simulatorul sa lucreze in-order.");
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Issue:inorder");
			this.MainContainer.Add (this.label6);
			global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.label6]));
			w20.X = 12;
			w20.Y = 186;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.IssueInorderCheckBox = new global::Gtk.CheckButton ();
			w3.SetTip (this.IssueInorderCheckBox, "forteaza simulatorul sa lucreze in-order.", "forteaza simulatorul sa lucreze in-order.");
			this.IssueInorderCheckBox.CanFocus = true;
			this.IssueInorderCheckBox.Name = "IssueInorderCheckBox";
			this.IssueInorderCheckBox.Label = global::Mono.Unix.Catalog.GetString ("Issue inorder");
			this.IssueInorderCheckBox.DrawIndicator = true;
			this.IssueInorderCheckBox.UseUnderline = true;
			this.MainContainer.Add (this.IssueInorderCheckBox);
			global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.IssueInorderCheckBox]));
			w21.X = 162;
			w21.Y = 181;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.IssueWidthComboBox = global::Gtk.ComboBox.NewText ();
			this.IssueWidthComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("4"));
			this.IssueWidthComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("8"));
			this.IssueWidthComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("16"));
			this.IssueWidthComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("32"));
			this.IssueWidthComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("64"));
			this.IssueWidthComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("128"));
			this.IssueWidthComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("256"));
			this.IssueWidthComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("512"));
			this.IssueWidthComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("1024"));
			w3.SetTip (this.IssueWidthComboBox, "seteaza numarul maxim de instructiuni ce vor fi\nsimultan decodificate într-un ciclu.", "seteaza numarul maxim de instructiuni ce vor fi\nsimultan decodificate într-un ciclu.");
			this.IssueWidthComboBox.Name = "IssueWidthComboBox";
			this.IssueWidthComboBox.Active = 0;
			this.MainContainer.Add (this.IssueWidthComboBox);
			global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.IssueWidthComboBox]));
			w22.X = 162;
			w22.Y = 145;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.DecodeWidthComboBox = global::Gtk.ComboBox.NewText ();
			this.DecodeWidthComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("4"));
			this.DecodeWidthComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("8"));
			this.DecodeWidthComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("16"));
			this.DecodeWidthComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("32"));
			this.DecodeWidthComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("64"));
			this.DecodeWidthComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("128"));
			this.DecodeWidthComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("256"));
			this.DecodeWidthComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("512"));
			this.DecodeWidthComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("1024"));
			w3.SetTip (this.DecodeWidthComboBox, "seteaza numarul de instructiuni ce vor fi\nsimultan decodificate.", "seteaza numarul de instructiuni ce vor fi\nsimultan decodificate.");
			this.DecodeWidthComboBox.Name = "DecodeWidthComboBox";
			this.DecodeWidthComboBox.Active = 0;
			this.MainContainer.Add (this.DecodeWidthComboBox);
			global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.DecodeWidthComboBox]));
			w23.X = 162;
			w23.Y = 111;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.FetchmplatTextBox = new global::Gtk.Entry ();
			w3.SetTip (this.FetchmplatTextBox, "seteaza latenta unei predictii eronate a unei\ninstructiuni de salt (procesul de \"recovery\").", "seteaza latenta unei predictii eronate a unei\ninstructiuni de salt (procesul de \"recovery\").");
			this.FetchmplatTextBox.WidthRequest = 50;
			this.FetchmplatTextBox.CanFocus = true;
			this.FetchmplatTextBox.Name = "FetchmplatTextBox";
			this.FetchmplatTextBox.Text = global::Mono.Unix.Catalog.GetString ("3");
			this.FetchmplatTextBox.IsEditable = true;
			this.FetchmplatTextBox.InvisibleChar = '●';
			this.MainContainer.Add (this.FetchmplatTextBox);
			global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.FetchmplatTextBox]));
			w24.X = 163;
			w24.Y = 81;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.FetchifqSizeComboBox = global::Gtk.ComboBox.NewText ();
			this.FetchifqSizeComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("4 "));
			this.FetchifqSizeComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("8 "));
			this.FetchifqSizeComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("16"));
			this.FetchifqSizeComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("32"));
			this.FetchifqSizeComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("64"));
			this.FetchifqSizeComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("128"));
			this.FetchifqSizeComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("256"));
			this.FetchifqSizeComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("512"));
			this.FetchifqSizeComboBox.AppendText (global::Mono.Unix.Catalog.GetString ("1024"));
			w3.SetTip (this.FetchifqSizeComboBox, "seteaza numarul de instructiuni ce vor fi extrase\nsimultan din cache / memorie principala.", "seteaza numarul de instructiuni ce vor fi extrase\nsimultan din cache / memorie principala.");
			this.FetchifqSizeComboBox.Name = "FetchifqSizeComboBox";
			this.FetchifqSizeComboBox.Active = 0;
			this.MainContainer.Add (this.FetchifqSizeComboBox);
			global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.FetchifqSizeComboBox]));
			w25.X = 163;
			w25.Y = 46;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label ();
			w3.SetTip (this.label4, "seteaza numarul maxim de instructiuni ce vor fi\nsimultan decodificate într-un ciclu.", "seteaza numarul maxim de instructiuni ce vor fi\nsimultan decodificate într-un ciclu.");
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Issue:width <insts>");
			this.MainContainer.Add (this.label4);
			global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.label4]));
			w26.X = 12;
			w26.Y = 150;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.mda = new global::Gtk.Label ();
			w3.SetTip (this.mda, "seteaza numarul de instructiuni ce vor fi\nsimultan decodificate.", "seteaza numarul de instructiuni ce vor fi\nsimultan decodificate.");
			this.mda.Name = "mda";
			this.mda.LabelProp = global::Mono.Unix.Catalog.GetString ("Decode:width <insts>");
			this.MainContainer.Add (this.mda);
			global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.mda]));
			w27.X = 12;
			w27.Y = 116;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			w3.SetTip (this.label2, "seteaza latenta unei predictii eronate a unei\ninstructiuni de salt (procesul de \"recovery\").", "seteaza latenta unei predictii eronate a unei\ninstructiuni de salt (procesul de \"recovery\").");
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Fetch:mplat <cycles>");
			this.MainContainer.Add (this.label2);
			global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.label2]));
			w28.X = 13;
			w28.Y = 86;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			w3.SetTip (this.label1, "seteaza numarul de instructiuni ce vor fi extrase\nsimultan din cache / memorie principala.", "seteaza numarul de instructiuni ce vor fi extrase\nsimultan din cache / memorie principala.");
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Fetch:ifqsize <size>");
			this.MainContainer.Add (this.label1);
			global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.label1]));
			w29.X = 13;
			w29.Y = 52;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Parametrii specifici nucleului de executie al \nprocesorului:");
			this.label5.UseUnderline = true;
			this.label5.Wrap = true;
			this.MainContainer.Add (this.label5);
			global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.label5]));
			w30.X = 14;
			w30.Y = 7;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Parametrii suplimentari (gasiti doar la sim-outorder nu si la simcache)\nce caracterizeaza interfata procesor - sistemul ierarhizat de\nmemorie:");
			this.MainContainer.Add (this.label14);
			global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.label14]));
			w31.X = 355;
			w31.Y = 8;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Cachedl1lat <cycles>");
			this.MainContainer.Add (this.label15);
			global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.label15]));
			w32.X = 355;
			w32.Y = 72;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Mem:width <bytes>");
			this.MainContainer.Add (this.label16);
			global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.label16]));
			w33.X = 355;
			w33.Y = 104;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Tlb:lat <cycles>");
			this.MainContainer.Add (this.label17);
			global::Gtk.Fixed.FixedChild w34 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.label17]));
			w34.X = 357;
			w34.Y = 136;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.Cachedl1latTextBox = new global::Gtk.Entry ();
			this.Cachedl1latTextBox.WidthRequest = 50;
			this.Cachedl1latTextBox.CanFocus = true;
			this.Cachedl1latTextBox.Name = "Cachedl1latTextBox";
			this.Cachedl1latTextBox.Text = global::Mono.Unix.Catalog.GetString ("1");
			this.Cachedl1latTextBox.IsEditable = true;
			this.Cachedl1latTextBox.InvisibleChar = '●';
			this.MainContainer.Add (this.Cachedl1latTextBox);
			global::Gtk.Fixed.FixedChild w35 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.Cachedl1latTextBox]));
			w35.X = 505;
			w35.Y = 68;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.MemwidthTextBox = new global::Gtk.Entry ();
			this.MemwidthTextBox.WidthRequest = 50;
			this.MemwidthTextBox.CanFocus = true;
			this.MemwidthTextBox.Name = "MemwidthTextBox";
			this.MemwidthTextBox.Text = global::Mono.Unix.Catalog.GetString ("1024");
			this.MemwidthTextBox.IsEditable = true;
			this.MemwidthTextBox.InvisibleChar = '●';
			this.MainContainer.Add (this.MemwidthTextBox);
			global::Gtk.Fixed.FixedChild w36 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.MemwidthTextBox]));
			w36.X = 505;
			w36.Y = 100;
			// Container child MainContainer.Gtk.Fixed+FixedChild
			this.TlblatTextBox = new global::Gtk.Entry ();
			this.TlblatTextBox.WidthRequest = 50;
			this.TlblatTextBox.CanFocus = true;
			this.TlblatTextBox.Name = "TlblatTextBox";
			this.TlblatTextBox.Text = global::Mono.Unix.Catalog.GetString ("256");
			this.TlblatTextBox.IsEditable = true;
			this.TlblatTextBox.InvisibleChar = '●';
			this.MainContainer.Add (this.TlblatTextBox);
			global::Gtk.Fixed.FixedChild w37 = ((global::Gtk.Fixed.FixedChild)(this.MainContainer [this.TlblatTextBox]));
			w37.X = 505;
			w37.Y = 131;
			this.Add (this.MainContainer);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 828;
			this.DefaultHeight = 467;
			this.Show ();
			this.SaveButton.Clicked += new global::System.EventHandler (this.OnSaveButtonClicked);
		}
	}
}
